openapi: 3.0.0
info:
  title: WHO API
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:5000'
paths:
  /some:
    parameters: []
    get:
      summary: Get Articles from WHO
      tags: []
      responses:
        '200':
          description: Article Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get Article Ethiopia Fever:
                  value:
                    startDate: '2020-01-01T00:00:00'
                    endDate: '2021-03-01T00:00:00'
                    location: Ethiopia
                    keywords: fever
        '404':
          description: User Not Found
          headers: {}
          content:
            application/json:
              schema:
                type: object
              examples:
                No start date:
                  value:
                    endDate: '2023-01-01T00:00:00'
                    location: Ethiopia
                    keywords: fever
      operationId: get-users-userId
      description: Gets articles from WHO
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
components:
  schemas:
    User:
      title: Ethiopia Fever
      type: object
      description: ''
      x-examples:
        Ethiopia Fever 200:
          startDate: '2020-01-01T00:00:00'
          endDate: '2021-03-01T00:00:00'
          location: Ethiopia
          keywords: fever
      properties:
        startDate:
          type: object
          description: Unique identifier for the given user.
        endDate:
          type: object
        location:
          type: string
        keywords:
          type: string
      required:
        - startDate
